try {
    hello();
} catch (error) {
    console.log(error);
};

try {
    anotherFunctio();
}catch {
    console.log('Esto es un error');
};